version: '1.0.{build}'
image: Visual Studio 2017
platform: Any CPU
configuration: Release
init:
  - cmd: git config --global core.autocrlf true
install:
  - cmd: docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
build_script:
  - ps: .\build.ps1
test: off